AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-copy
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::526246055622:role/service-role/search-photos-role-447jpu2a"
      Events: 
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos-copy
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "aarn:aws:iam::526246055622:role/service-role/LF1-role-m43dhibm"
      Environment:
        Variables:
          REGION: us-east-1
